#!/bin/bash

FOCUS_DESKTOP=1
TOGGLE_LAYOUT=2
SHOW_AGENDA=3
SHOW_EMAILS=4

err() {
	echo "$1"
	exit 1
}

usage() {
	echo "usage: panel_command [command] [value]"
	echo
	echo "Options:"
	echo "	 -f, --focus-desktop  - switch to desktop name"
	echo "	 -l, --toggle-layout  - toggle layout of current desktop"
	echo "	 -a, --agenda         - show popup with today's agenda"
	echo "	 -e, --emails         - show popup with unread emails"
	echo "	 -h, --help           - display this"
	exit
}

case $1 in
	'-f'|'--focus-desktop')
		[ -z "$2" ] && err "No desktop name specified"
		COMMAND=$FOCUS_DESKTOP
		ARGN="${2}"
		;;
	'-l'|'--toggle-layout')
		COMMAND=$TOGGLE_LAYOUT
		;;
	'-a'|'--agenda')
		COMMAND=$SHOW_AGENDA
		;;
	'-e'|'--emails')
		COMMAND=$SHOW_EMAILS
		;;
	''|'-h'|'--help'|*)
		usage
		exit
		;;
esac

# Ensure the command is something we want to run
case $COMMAND in
	$FOCUS_DESKTOP)
		bspc config auto_alternate false
		bspc desktop -f $ARGN
		bspc config auto_alternate true
		;;
	$TOGGLE_LAYOUT)
		bspc desktop -l next
		;;
	$SHOW_AGENDA)
		/home/esimsig/.config/bspwm/panel/popups/khal-agenda &
		;;
	$SHOW_EMAILS)
		/home/esimsig/.config/bspwm/panel/popups/email-list &
		;;
	*)
		;;
esac
