#!/bin/bash
TMPDIR=$(mktemp -d /tmp/git-latexdiff.XXXXXX)
latexdiff -p ~/.dotfiles/common/git/auxillary/latexdiff-preamble.tex "$1" "$2" > $TMPDIR/diff.tex
pdflatex -interaction nonstopmode -output-directory $TMPDIR $TMPDIR/diff.tex
pdflatex -interaction nonstopmode -output-directory $TMPDIR $TMPDIR/diff.tex
$PDFVIEWER $TMPDIR/diff.pdf
rm -rf $TMPDIR
